### PR TITLE
Add masks for major/minor identifiers that vary over time

### PR DESCRIPTION
**Pull request by PeteBa**
Hi, and to start a thanks for this great package that now has my iBeacon streaming into Home Assistant. Magic!

The iBeacon I have multiplexes the Battery Level on to the Minor ID of the device. I think there are a few that are doing (or provide the option) to do this. So I took a steer from the BLE "use_mac" approach to add a similar concept to iBeacons. In this case, I have added "major_mask" and "minor_mask" to allow the end-user to mask out major/minor field bits that may vary over time. In my case, the iBeacon uses the upper two bytes of the minor field to carry 0-100 for the battery level so I want to mask out that portion with 0x00FF as follows:

`  "ibeacon": {
    "enabled": true,
    "minor_mask": "0x00FF",
    "channel": "room_presence",
    "max_distance": 0,
    "whitelist": ["UUID-1-1"],
    "system_noise": 0.01,
    "measurement_noise": 3
  },
`

This gives me a constant device_id to subscribe to with the mqqt_room component in Home Assistant. It also gives me the unadulterated major/minor fields on the channel so that I can extract the battery level on the HA side. Perfect.

Lastly, I moved the "id" modification (use_mac and minor/major_mask) before the whitelist is checked. This way you can use the mac address in the case of BLE or masked major/minor in the case of iBeacons in the whitelist.

Again, this is a great component and many thanks for the efforts. Let me know if any of the above isnt in line with how you want the code and I'll happily modify/alter as needed.

### CODE REVIEW

**Comment by mKeRix** [comment]
Smart additions, thanks for the great work! I'll merge this to `dev` in a moment. Once I've updated the documentation I will push this into a new release, presumably by the end of the week. :)

**Comment by PeteBa** [comment]
Fantastic. Thanks.

**Comment by PeteBa** [comment]
Oh, quick question. Why didn't mqqt_room end up as a device_tracker in HA ? I've read your HA pull request which suggests that it was considered but ultimately balloob suggested an independent component. Not a big deal, just curious ... as I want to understand more about HA before starting to develop my own components 8). Thanks again.

**Comment by mKeRix** [comment]
My pull request (home-assistant/home-assistant#2913) originally intended to add an attribute to the device trackers that contains the room data. balloob didn't want to add the attribute to their parent class because it wouldn't be used by the majority of those components and he disliked having special attributes in generic classes. It's understandable, but I still think the first implementation would've fit in better overall. Maybe they'll revise their decision ones more specific implementations start popping up.

When it comes to architecture and contributing to HASS their dev chat rooms are super helpful and the place to discuss this stuff in. So if you're unsure about something feel free to drop in there :)

**Comment by mKeRix** [comment]
Quick update: unfortunately my weekend was packed, but I'll try to get this done by Wednesday at latest. Sorry!

**Pull request merged**
